services:
  grafana:
    container_name: grafana
    restart: always
    image: "grafana/grafana:11.5.2"
    ports:
      - "6666:6666"
    environment:
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel,jdbranham-diagram-panel"
      - GF_SECURITY_ADMIN_PASSWORD="bD9bNK7Z"
      - GF_SECURITY_ADMIN_USER="bimarz"
    volumes:
      - "./grafanadata:/etc/grafana:rw"

  prometheus:
    container_name: prometheus
    image: "prom/prometheus:v3.2.1"
    command:
      - "--config.file=./prometheusdata/prometheus.yml"
      - "--web.external-url=http://prometheus:9090/"
      - "--web.route-prefix=/"
    restart: always
    ports:
      - "1212:1212"
    volumes:
      - "./prometheusdata:/etc/prometheus:rw"
      - "./prometheusdb:/prometheus/data:rw"
