global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules'

scrape_configs:
  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
      - targets: ['metrics.domain.com:8899']

